# Site settings
title: Isabela Sampaio | UX designer & front-end developer
email: isapsampaio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Isabela Sampaio - User experience designer and front-end developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
css_folder:  'assets/css'
js_folder:  'assets/js'
img_folder:  'assets/img'
font_folder:  'assets/fonts'

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/

# Build settings
markdown: kramdown
highlighter: rouge
